# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest
  name: my-pool
steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'
# # Copy Files
- task: CopyFiles@2
  inputs:
    sourceFolder: $(Build.SourcesDirectory)
    contents: '*.zip' 
    targetFolder: $(Build.ArtifactStagingDirectory)



- task: UniversalPackages@0
  displayName: 'Upload Artifact'
  inputs:
    command: publish
    vstsFeedPublish: '7bb0c2a2-923a-443c-ae22-ad3ebc5c70ea/6dcb044c-bd40-451d-ab60-469c18ef7eb0'
    vstsFeedPackagePublish: 'my-artifact'
- task: CmdLine@2
  inputs:
    script: |
      cd ~/weightTracker-ansible2
      echo "Be aware that the host variable is in hosts.txt file
      pghost: \"$(pghost)\"
      pg_username: \"$(pg_username)\"
      pg_password: \"$(pg_password")\"
      LB_front_ip: \"$(LB_front_ip)\"